services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres_a
    environment:
      - 'POSTGRES_DB=superpoder'
      - 'POSTGRES_PASSWORD=superpoder'
      - 'POSTGRES_USER=superpoder'
    ports:
      - '5432:5432'
